apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  tokenSecret:
    name: doppler-token-shared
  managedSecret:
    name: monitoring-secrets
    namespace: monitoring
  project: k8s
  config: prd
  processors:
    DB_MINIO_ENDPOINT:
      asName: S3_ENDPOINT
      type: plain
    S3_MIMIR_PASSWORD:
      asName: S3_MIMIR_PASSWORD
      type: plain
    S3_PYROSCOPE_PASSWORD:
      asName: S3_PYROSCOPE_PASSWORD
      type: plain
    DB_OBS_POSTGRESQL__HOST:
      asName: GRAFANA_DB_HOST
      type: plain
    GRAFANA_POSTGRESQL__NAME:
      asName: GRAFANA_DB_NAME
      type: plain
    GRAFANA_POSTGRESQL__USER:
      asName: GRAFANA_DB_USER
      type: plain
    GRAFANA_POSTGRESQL__PASSWORD:
      asName: GRAFANA_DB_PASSWORD
      type: plain
