# 官方 traefik helm chart 的自定义 values
ports:
  web:
    redirectTo: websecure
  websecure:
    tls:
      enabled: true

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
  kubernetesIngress:
    enabled: true
