apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: alertmanager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: 'ghcr.io/prometheus-community/charts'
    chart: alertmanager
    targetRevision: 1.42.0
    helm:
      valuesObject:
        extraEnv:
          - name: TZ
            value: Asia/Shanghai
        extraSecretMounts:
          - name: slack-webhook
            mountPath: /etc/alertmanager/secrets/slack-webhook
            secretName: monitoring-secrets
            readOnly: true
        persistence:
          enabled: false
        config:
          global:
            slack_api_url_file: /etc/alertmanager/secrets/slack-webhook/SLACK_WEBHOOK_URL
          route:
            receiver: slack
            group_by: ['alertname', 'cluster', 'service']
            group_wait: 30s
            group_interval: 5m
            repeat_interval: 12h
          receivers:
            - name: slack
              slack_configs:
                - send_resolved: true
                  title: |-
                    [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }}
                  text: >-
                    {{ range .Alerts -}}
                    *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}
                    *Description:* {{ .Annotations.description }}
                    *Details:*
                      {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
                      {{ end }}
                    {{ end }}
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
            - host: alertmanager.646499453.xyz
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: wildcards-646499453-xyz-tls
              hosts:
                - alertmanager.646499453.xyz
          annotations:
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: "Alertmanager"
            gethomepage.dev/description: "Alert Management"
            gethomepage.dev/group: "Dashboards"
            gethomepage.dev/icon: "sh-prometheus.svg"
            gethomepage.dev/href: "https://alertmanager.646499453.xyz:8443"
            gethomepage.dev/pod-selector: "app.kubernetes.io/name=alertmanager"
            traefik.ingress.kubernetes.io/router.middlewares: monitoring-lan-only-allowlist@kubernetescrd