apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: umami
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: monitoring
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  sources:
  - repoURL: 'https://repo.helmforge.dev'
    chart: umami
    targetRevision: 2.3.0
    helm:
      valuesObject:
        ingress:
          enabled: true
          ingressClassName: traefik
          hosts:
          - host: umami.646499453.xyz
            paths:
            - path: /
              pathType: Prefix
          tls:
          - secretName: wildcards-646499453-xyz-tls
            hosts:
            - umami.646499453.xyz
          annotations:
            gethomepage.dev/enabled: "true"
            gethomepage.dev/name: "Umami"
            gethomepage.dev/description: "Web Analytics"
            gethomepage.dev/group: "Monitoring"
            gethomepage.dev/icon: "sh-umami.svg"
            gethomepage.dev/href: "https://umami.646499453.xyz"

        postgresql:
          enabled: false

        initContainers:
          waitForDatabase:
            enabled: false

        database:
          external:
            host: $(DB_OBS_POSTGRESQL__HOST)
            name: $(UMAMI_DB_NAME)
            username: $(UMAMI_DB_USER)
            existingSecret: monitoring-secrets
            existingSecretPasswordKey: UMAMI_DB_PASSWORD

        umami:
          existingSecret: monitoring-secrets
          existingSecretKey: UMAMI_APP_SECRET
          extraEnv:
            - name: DB_OBS_POSTGRESQL__HOST
              valueFrom:
                secretKeyRef:
                  name: monitoring-secrets
                  key: DB_OBS_POSTGRESQL__HOST
            - name: UMAMI_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: monitoring-secrets
                  key: UMAMI_DB_NAME
            - name: UMAMI_DB_USER
              valueFrom:
                secretKeyRef:
                  name: monitoring-secrets
                  key: UMAMI_DB_USER
