apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: cloudflare-ddns-secrets
  namespace: ddns
spec:
  tokenSecret:
    name: doppler-token-shared
  managedSecret:
    name: cloudflare-ddns-secrets
    namespace: ddns
  project: k8s
  config: prd
  processors:
    CLOUDFLARE_API_KEY:
      asName: CLOUDFLARE_API_TOKEN
      type: plain
