# We will instruct the Chart to use our Doppler generated secret
externalSecret: "cloudflare-ddns-secrets"

# Configuration for aureum-cloud/cloudflare-ddns
config:
  configJson: |
    {
      "cloudflare": [
        {
          "authentication": {
            "api_token": "${CLOUDFLARE_API_TOKEN}"
          },
          "zone_id": "3a55ed5932efda7c5ebbd2146f40c77f",
          "subdomains": [
            {
              "name": "langshi",
              "proxied": false
            }
          ]
        }
      ],
      "a": true,
      "aaaa": false,
      "purgeUnknownRecords": false,
      "ttl": 300
    }

# Disable chart's own secret creation, we use Doppler
secrets:
  cloudflareApiToken: ""
