apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: authentik-db-credentials
  namespace: authentik
spec:
  managedSecret:
    name: authentik-db-credentials
  tokenSecret:
    name: doppler-operator-token
    namespace: doppler-operator-system
  project: k8s
  config: prd_argocd
  format: plain
  nameMapping:
    AUTHENTIK_DB_PASSWORD: AUTHENTIK_POSTGRESQL__PASSWORD
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  managedSecret:
    name: authentik-secret-key
  tokenSecret:
    name: doppler-operator-token
    namespace: doppler-operator-system
  project: k8s
  config: prd_argocd
  format: plain
  nameMapping:
    AUTHENTIK_SECRET_KEY: AUTHENTIK_SECRET_KEY
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: authentik-oidc-credentials
  namespace: authentik
spec:
  managedSecret:
    name: authentik-oidc-credentials
  tokenSecret:
    name: doppler-operator-token
    namespace: doppler-operator-system
  project: k8s
  config: prd_argocd
  format: plain
  nameMapping:
    AUTHENTIK_OIDC_ARGOCD_SECRET: ARGOCD_CLIENT_SECRET
    AUTHENTIK_OIDC_GRAFANA_SECRET: GRAFANA_CLIENT_SECRET
    AUTHENTIK_OIDC_HA_LANGSHI_SECRET: HOMEASSISTANT_LANGSHI_CLIENT_SECRET
    AUTHENTIK_OIDC_HA_LVDI_SECRET: HOMEASSISTANT_LVDI_CLIENT_SECRET
    AUTHENTIK_OIDC_PROXMOX_SECRET: PROXMOX_CLIENT_SECRET
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: authentik-blueprint-secrets
  namespace: authentik
spec:
  managedSecret:
    name: authentik-blueprint-secrets
  tokenSecret:
    name: doppler-operator-token
    namespace: doppler-operator-system
  project: k8s
  config: prd_argocd
  format: plain
  nameMapping:
    AUTHENTIK_USER_LIANA_PASSWORD: LIANA_PASSWORD
    AUTHENTIK_USER_LOU_PASSWORD: LOU_PASSWORD
    PBS_SYSTEM_PASSWORD: PBS_PASSWORD
    TRUENAS_API_KEY: TRUENAS_PASSWORD
