apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: authentik-db-credentials
  namespace: authentik
spec:
  managedSecret:
    name: authentik-db-credentials
  tokenSecret:
    name: doppler-operator-token
  project: k8s
  config: prd_argocd
  secrets:
    - AUTHENTIK_MAIN_PG_PASSWORD
  processors:
    AUTHENTIK_MAIN_PG_PASSWORD:
      type: plain
      asName: AUTHENTIK_POSTGRESQL__PASSWORD
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  managedSecret:
    name: authentik-secret-key
  tokenSecret:
    name: doppler-operator-token
  project: k8s
  config: prd_argocd
  secrets:
    - AUTHENTIK_SECRET_KEY
  processors:
    AUTHENTIK_SECRET_KEY:
      type: plain
      asName: AUTHENTIK_SECRET_KEY
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: authentik-oidc-credentials
  namespace: authentik
spec:
  managedSecret:
    name: authentik-oidc-credentials
  tokenSecret:
    name: doppler-operator-token
  project: k8s
  config: prd_argocd
  secrets:
    - AUTHENTIK_OIDC_ARGOCD_SECRET
    - AUTHENTIK_OIDC_GRAFANA_SECRET
    - AUTHENTIK_OIDC_HA_LANGSHI_SECRET
    - AUTHENTIK_OIDC_HA_LVDI_SECRET
    - AUTHENTIK_OIDC_PROXMOX_SECRET
  processors:
    AUTHENTIK_OIDC_ARGOCD_SECRET:
      type: plain
      asName: ARGOCD_CLIENT_SECRET
    AUTHENTIK_OIDC_GRAFANA_SECRET:
      type: plain
      asName: GRAFANA_CLIENT_SECRET
    AUTHENTIK_OIDC_HA_LANGSHI_SECRET:
      type: plain
      asName: HOMEASSISTANT_LANGSHI_CLIENT_SECRET
    AUTHENTIK_OIDC_HA_LVDI_SECRET:
      type: plain
      asName: HOMEASSISTANT_LVDI_CLIENT_SECRET
    AUTHENTIK_OIDC_PROXMOX_SECRET:
      type: plain
      asName: PROXMOX_CLIENT_SECRET
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: authentik-blueprint-secrets
  namespace: authentik
spec:
  managedSecret:
    name: authentik-blueprint-secrets
  tokenSecret:
    name: doppler-operator-token
  project: k8s
  config: prd_argocd
  secrets:
    - AUTHENTIK_USER_LIANA_PASSWORD
    - AUTHENTIK_USER_LOU_PASSWORD
    - PBS_SYSTEM_PASSWORD
    - TRUENAS_API_KEY
  processors:
    AUTHENTIK_USER_LIANA_PASSWORD:
      type: plain
      asName: LIANA_PASSWORD
    AUTHENTIK_USER_LOU_PASSWORD:
      type: plain
      asName: LOU_PASSWORD
    PBS_SYSTEM_PASSWORD:
      type: plain
      asName: PBS_PASSWORD
    TRUENAS_API_KEY:
      type: plain
      asName: TRUENAS_PASSWORD
