apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: ddns-updater-secrets
  namespace: ddns
spec:
  tokenSecret:
    name: doppler-token-shared
    namespace: argocd
  managedSecret:
    name: ddns-updater-secrets
    namespace: ddns
  project: k8s
  config: prd
  processors:
    CLOUDFLARE_API_KEY:
      asName: CLOUDFLARE_API_KEY
      type: plain
