apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  tokenSecret:
    name: doppler-token-shared
  managedSecret:
    name: authentik-secrets
    namespace: authentik
  project: k8s
  config: prd
  # Only sync the needed secrets
  nameMap:
    DB_AUTH_POSTGRESQL__HOST: AUTHENTIK_POSTGRESQL__HOST
    AUTHENTIK_POSTGRESQL__NAME: AUTHENTIK_POSTGRESQL__NAME
    AUTHENTIK_POSTGRESQL__USER: AUTHENTIK_POSTGRESQL__USER
    DB_AUTH_POSTGRESQL__PASSWORD: AUTHENTIK_POSTGRESQL__PASSWORD
    DB_AUTH_REDIS__HOST: AUTHENTIK_REDIS__HOST
    DB_AUTH_REDIS__PASSWORD: AUTHENTIK_REDIS__PASSWORD
    AUTHENTIK_ERROR_REPORTING__ENABLED: AUTHENTIK_ERROR_REPORTING__ENABLED
    AUTHENTIK_SECRET_KEY: AUTHENTIK_SECRET_KEY
