apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  tokenSecret:
    name: doppler-token-shared
  managedSecret:
    name: authentik-secrets
    namespace: authentik
  project: k8s
  config: prd
  # Only sync the needed secrets
  processors:
    DB_AUTH_POSTGRESQL__HOST:
      asName: AUTHENTIK_POSTGRESQL__HOST
      type: plain
    AUTHENTIK_POSTGRESQL__NAME:
      asName: AUTHENTIK_POSTGRESQL__NAME
      type: plain
    AUTHENTIK_POSTGRESQL__USER:
      asName: AUTHENTIK_POSTGRESQL__USER
      type: plain
    AUTHENTIK_POSTGRESQL__PASSWORD:
      asName: AUTHENTIK_POSTGRESQL__PASSWORD
      type: plain
    DB_AUTH_REDIS__HOST:
      asName: AUTHENTIK_REDIS__HOST
      type: plain
    DB_AUTH_REDIS__PASSWORD:
      asName: AUTHENTIK_REDIS__PASSWORD
      type: plain
    AUTHENTIK_ERROR_REPORTING__ENABLED:
      asName: AUTHENTIK_ERROR_REPORTING__ENABLED
      type: plain
    AUTHENTIK_SECRET_KEY:
      asName: AUTHENTIK_SECRET_KEY
      type: plain
