apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '20'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: traefik
  namespace: argocd
spec:
  destination:
    namespace: traefik
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: traefik
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 40.2.0
    helm:
      values: |
        api:
          dashboard: true
          insecure: true
        metrics:
          prometheus:
            addEntryPointsLabels: true
            addRoutersLabels: true
            addServicesLabels: true
            entryPoint: metrics
            service:
              enabled: true
            serviceMonitor:
              enabled: true
              additionalLabels:
                release: kube-prometheus-stack
        deployment:
          kind: DaemonSet
        extraObjects:
        - apiVersion: traefik.io/v1alpha1
          kind: Middleware
          metadata:
            name: authentik-forward-auth
            namespace: traefik
          spec:
            forwardAuth:
              address: http://authentik-server.authentik.svc.cluster.local/outpost.goauthentik.io/auth/traefik
              maxResponseBodySize: 4194304
              authResponseHeaders:
              - X-authentik-username
              - X-authentik-groups
              - X-authentik-email
              - X-authentik-name
              - X-authentik-uid
              trustForwardHeader: true
        ingressRoute:
          dashboard:
            annotations:
              gethomepage.dev/app: traefik
              gethomepage.dev/description: Reverse Proxy Dashboard
              gethomepage.dev/enabled: 'true'
              gethomepage.dev/group: Networking
              gethomepage.dev/href: https://traefik.646499453.xyz:8443
              gethomepage.dev/icon: traefik
              gethomepage.dev/name: Traefik
              gethomepage.dev/pod-selector: app.kubernetes.io/name=traefik
              gethomepage.dev/widget.type: traefik
              gethomepage.dev/widget.url: http://traefik.traefik.svc.cluster.local:9000
            enabled: true
            entryPoints:
            - websecure8443
            matchRule: Host(`traefik.646499453.xyz`)
            middlewares:
            - name: authentik-forward-auth
            tls:
              secretName: wildcard-646499453-crt
        ports:
          ssh:
            expose:
              default: true
            exposedPort: 22
            hostPort: 22
            port: 22
            protocol: TCP
          sshpassthrough:
            expose:
              default: true
            exposedPort: 9443
            hostPort: 9443
            port: 9443
            protocol: TCP
          traefik:
            expose:
              default: true
            exposedPort: 9000
            port: 9000
            protocol: TCP
          web:
            hostPort: 80
            port: 8000
          websecure:
            hostPort: 443
            port: 8443
          # Dual-port listening for solving OIDC rewrite issue
          websecure8443:
            hostPort: 8443
            port: 8444
            expose:
              default: true
            protocol: TCP
        providers:
          kubernetesCRD:
            allowExternalNameServices: true
        service:
          type: ClusterIP
        updateStrategy:
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
          type: RollingUpdate
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
