apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    link.argocd.argoproj.io/external-link: https://authentik.646499453.xyz:8443
spec:
  project: security
  sources:
    - repoURL: 'https://charts.goauthentik.io'
      chart: authentik
      targetRevision: 2026.5.6
      helm:
        valueFiles:
          - $values/argocd/configs/security/authentik/values.yaml
    - repoURL: 'https://github.com/loushomelab/homelab-talos-iac.git'
      targetRevision: HEAD
      ref: values
    - repoURL: 'https://github.com/loushomelab/homelab-talos-iac.git'
      targetRevision: HEAD
      path: argocd/configs/security/authentik/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
