apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    link.argocd.argoproj.io/external-link: https://authentik.646499453.xyz:8443
spec:
  project: security
  sources:
  - repoURL: 'https://charts.goauthentik.io'
    chart: authentik
    targetRevision: 2026.8.0
    helm:
      valuesObject:
        authentik:
          enabled: true
          log_level: info
          postgresql:
            enabled: false
          redis:
            enabled: false
        server:
          enabled: true
          env:
          - name: TZ
            value: Asia/Shanghai
          envFrom:
          - secretRef:
              name: authentik-secrets
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
            - authentik.646499453.xyz
            paths:
            - /
            pathType: Prefix
            tls:
            - secretName: wildcards-646499453-xyz-tls
              hosts:
              - authentik.646499453.xyz
            annotations:
              gethomepage.dev/enabled: "true"
              gethomepage.dev/name: "Authentik"
              gethomepage.dev/description: "SSO & Identity Provider"
              gethomepage.dev/group: "Identity"
              gethomepage.dev/icon: "authentik.png"
              gethomepage.dev/href: "https://authentik.646499453.xyz:8443"
              gethomepage.dev/pod-selector: "app.kubernetes.io/name=authentik,app.kubernetes.io/component=server"
              gethomepage.dev/app: "authentik"
              gethomepage.dev/widget.type: "authentik"
              gethomepage.dev/widget.version: "2"
              gethomepage.dev/widget.url: "https://authentik.646499453.xyz:8443"
              gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_AUTHENTIK_API_KEY}}"
        worker:
          enabled: true
          env:
          - name: TZ
            value: Asia/Shanghai
          envFrom:
          - secretRef:
              name: authentik-secrets
        blueprints:
          configMaps:
          - authentik-blueprint-pve
          - authentik-blueprint-webauthn
          - authentik-blueprint-apps
  - repoURL: 'https://github.com/loushomelab/homelab-talos-iac.git'
    targetRevision: HEAD
    path: argocd/configs/security/authentik/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
