---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secrets
  namespace: authentik
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-store
  target:
    name: authentik-secrets
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_POSTGRESQL__HOST
      remoteRef:
        key: DB_AUTH_POSTGRESQL__HOST
    - secretKey: AUTHENTIK_POSTGRESQL__NAME
      remoteRef:
        key: AUTHENTIK_POSTGRESQL__NAME
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: AUTHENTIK_POSTGRESQL__USER
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: AUTHENTIK_POSTGRESQL__PASSWORD
    - secretKey: AUTHENTIK_REDIS__HOST
      remoteRef:
        key: DB_AUTH_REDIS__HOST
    - secretKey: AUTHENTIK_REDIS__PASSWORD
      remoteRef:
        key: DB_AUTH_REDIS__PASSWORD
    - secretKey: AUTHENTIK_ERROR_REPORTING__ENABLED
      remoteRef:
        key: AUTHENTIK_ERROR_REPORTING__ENABLED
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: AUTHENTIK_SECRET_KEY
    - secretKey: AUTHENTIK_OIDC_PROXMOX_SECRET
      remoteRef:
        key: AUTHENTIK_OIDC_PROXMOX_SECRET
    - secretKey: AUTHENTIK_OIDC_ARGOCD_SECRET
      remoteRef:
        key: AUTHENTIK_OIDC_ARGOCD_SECRET
    - secretKey: AUTHENTIK_OIDC_GRAFANA_SECRET
      remoteRef:
        key: AUTHENTIK_OIDC_GRAFANA_SECRET
    - secretKey: AUTHENTIK_OIDC_HOMEPAGE_SECRET
      remoteRef:
        key: AUTHENTIK_OIDC_HOMEPAGE_SECRET
    - secretKey: AUTHENTIK_OIDC_PULSE_SECRET
      remoteRef:
        key: AUTHENTIK_OIDC_PULSE_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-store
  target:
    name: homepage-secrets
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_GRAFANA_USERNAME
      remoteRef:
        key: HOMEPAGE_VAR_GRAFANA_USERNAME
    - secretKey: HOMEPAGE_VAR_GRAFANA_PASSWORD
      remoteRef:
        key: HOMEPAGE_VAR_GRAFANA_PASSWORD
    - secretKey: HOMEPAGE_VAR_PROXMOX_USERNAME
      remoteRef:
        key: HOMEPAGE_VAR_PROXMOX_USERNAME
    - secretKey: HOMEPAGE_VAR_PROXMOX_PASSWORD
      remoteRef:
        key: HOMEPAGE_VAR_PROXMOX_PASSWORD
    - secretKey: HOMEPAGE_VAR_SYNOLOGY_USERNAME
      remoteRef:
        key: HOMEPAGE_VAR_SYNOLOGY_USERNAME
    - secretKey: HOMEPAGE_VAR_SYNOLOGY_PASSWORD
      remoteRef:
        key: HOMEPAGE_VAR_SYNOLOGY_PASSWORD
    - secretKey: HOMEPAGE_VAR_TRUENAS_API_KEY
      remoteRef:
        key: HOMEPAGE_VAR_TRUENAS_API_KEY
    - secretKey: HOMEPAGE_VAR_PBS_USERNAME
      remoteRef:
        key: HOMEPAGE_VAR_PBS_USERNAME
    - secretKey: HOMEPAGE_VAR_PBS_PASSWORD
      remoteRef:
        key: HOMEPAGE_VAR_PBS_PASSWORD
    - secretKey: HOMEPAGE_VAR_HASS_LANGSHI_TOKEN
      remoteRef:
        key: HOMEPAGE_VAR_HASS_LANGSHI_TOKEN
    - secretKey: HOMEPAGE_VAR_AUTHENTIK_API_KEY
      remoteRef:
        key: HOMEPAGE_VAR_AUTHENTIK_API_KEY
    - secretKey: HOMEPAGE_VAR_ARGOCD_TOKEN
      remoteRef:
        key: HOMEPAGE_VAR_ARGOCD_TOKEN
    - secretKey: HOMEPAGE_VAR_UNIFI_API_KEY
      remoteRef:
        key: HOMEPAGE_VAR_UNIFI_API_KEY
    - secretKey: HOMEPAGE_VAR_PULSE_API_KEY
      remoteRef:
        key: HOMEPAGE_VAR_PULSE_API_KEY
    - secretKey: HOMEPAGE_AUTH_SECRET
      remoteRef:
        key: HOMEPAGE_AUTH_SECRET
    - secretKey: HOMEPAGE_OIDC_CLIENT_SECRET
      remoteRef:
        key: AUTHENTIK_OIDC_HOMEPAGE_SECRET
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: monitoring-secrets
  namespace: monitoring
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-store
  target:
    name: monitoring-secrets
    creationPolicy: Owner
  data:
    - secretKey: S3_ENDPOINT
      remoteRef:
        key: DB_MINIO_ENDPOINT
    - secretKey: SLACK_WEBHOOK_URL
      remoteRef:
        key: SLACK_WEBHOOK_URL
    - secretKey: S3_MIMIR_ACCESS_KEY
      remoteRef:
        key: S3_MIMIR_ACCESS_KEY
    - secretKey: S3_MIMIR_SECRET_KEY
      remoteRef:
        key: S3_MIMIR_SECRET_KEY
    - secretKey: S3_PYROSCOPE_ACCESS_KEY
      remoteRef:
        key: S3_PYROSCOPE_ACCESS_KEY
    - secretKey: S3_PYROSCOPE_SECRET_KEY
      remoteRef:
        key: S3_PYROSCOPE_SECRET_KEY
    - secretKey: DB_OBS_POSTGRESQL__HOST
      remoteRef:
        key: DB_OBS_POSTGRESQL__HOST
    - secretKey: GRAFANA_DB_NAME
      remoteRef:
        key: GRAFANA_POSTGRESQL__NAME
    - secretKey: GRAFANA_DB_USER
      remoteRef:
        key: GRAFANA_POSTGRESQL__USER
    - secretKey: GRAFANA_DB_PASSWORD
      remoteRef:
        key: GRAFANA_POSTGRESQL__PASSWORD
    - secretKey: UMAMI_DB_NAME
      remoteRef:
        key: UMAMI_POSTGRESQL__NAME
    - secretKey: UMAMI_DB_USER
      remoteRef:
        key: UMAMI_POSTGRESQL__USER
    - secretKey: UMAMI_DB_PASSWORD
      remoteRef:
        key: UMAMI_POSTGRESQL__PASSWORD
    - secretKey: UMAMI_APP_SECRET
      remoteRef:
        key: UMAMI_APP_SECRET
    - secretKey: PULSE_AUTH_USER
      remoteRef:
        key: PULSE_AUTH_USER
    - secretKey: PULSE_AUTH_PASS
      remoteRef:
        key: PULSE_AUTH_PASS
    - secretKey: AUTHENTIK_OIDC_PULSE_SECRET
      remoteRef:
        key: AUTHENTIK_OIDC_PULSE_SECRET
    - secretKey: PULSE_INIT_CONFIG_DATA
      remoteRef:
        key: PULSE_INIT_CONFIG_DATA
    - secretKey: PULSE_INIT_CONFIG_PASSPHRASE
      remoteRef:
        key: PULSE_INIT_CONFIG_PASSPHRASE
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns-secrets
  namespace: ddns
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-store
  target:
    name: cloudflare-ddns-secrets-env
    creationPolicy: Owner
  data:
    - secretKey: API_KEY
      remoteRef:
        key: CLOUDFLARE_API_TOKEN
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-secrets
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-store
  target:
    name: argocd-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        accounts.homepage.tokens: '[{"id":"62e71829-7cf8-4748-a10b-7549ec75e203","iat":1786780128}]'
        oidc.authentik.clientSecret: '{{ .authentik_secret }}'
        server.secretkey: '{{ .server_secretkey }}'
  data:
    - secretKey: authentik_secret
      remoteRef:
        key: AUTHENTIK_OIDC_ARGOCD_SECRET
    - secretKey: server_secretkey
      remoteRef:
        key: ARGOCD_SERVER_SECRETKEY
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: doppler-cluster-store
  target:
    name: cloudflare-api-token
    creationPolicy: Owner
  data:
    - secretKey: CLOUDFLARE_API_TOKEN
      remoteRef:
        key: CLOUDFLARE_API_TOKEN

