apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare
spec:
  acme:
    email: 6hmp547n4d@privaterelay.appleid.com
    privateKeySecretRef:
      name: cloudflare-letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cloudflare-secret
              key: CLOUDFLARE_API_TOKEN
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-646499453-ca
  namespace: cert-manager
spec:
  secretName: wildcard-646499453-crt
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  issuerRef:
    name: cloudflare
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - "*.646499453.xyz"
    - "646499453.xyz"
