apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: cloudflare-secret
  namespace: cert-manager
spec:
  managedSecret:
    name: cloudflare-secret
  tokenSecret:
    name: doppler-operator-token
  project: k8s
  config: argocd 
