apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-xyz
  namespace: argocd
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "ArgoCD"
    gethomepage.dev/description: "GitOps Continuous Delivery"
    gethomepage.dev/group: "CI/CD"
    gethomepage.dev/icon: "argo-cd.png"
    gethomepage.dev/href: "https://argocd.646499453.xyz:8443"
    gethomepage.dev/pod-selector: "app.kubernetes.io/name=argocd-server"
    gethomepage.dev/widget.type: "argocd"
    gethomepage.dev/widget.url: "http://argocd-server.argocd.svc.cluster.local:80"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_ARGOCD_TOKEN}}"
    gethomepage.dev/widget.fields: '["apps", "synced", "outOfSync", "healthy"]'
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.646499453.xyz`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls:
    secretName: wildcards-646499453-xyz-tls
