apiVersion: v1
kind: Service
metadata:
  name: pbs
  namespace: traefik
spec:
  type: ExternalName
  externalName: 192.168.50.154
  ports:
    - name: https
      port: 8007
      targetPort: 8007
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pbs
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`pbs.pve.646499453.xyz`)
      services:
        - name: pbs
          port: 8007
  tls:
    passthrough: true
