apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: pbs-insecure-transport
  namespace: traefik
spec:
  insecureSkipVerify: true
---
apiVersion: v1
kind: Service
metadata:
  name: pbs
  namespace: traefik
spec:
  ports:
    - name: https
      port: 8007
      targetPort: 8007
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: pbs
  namespace: traefik
subsets:
  - addresses:
      - ip: 192.168.50.154
    ports:
      - name: https
        port: 8007
        protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: pbs
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`pbs.pve.646499453.xyz`)
      kind: Rule
      services:
        - name: pbs
          port: 8007
          scheme: https
          serversTransport: pbs-insecure-transport
  tls:
    secretName: wildcards-646499453-xyz-tls
