# ==========================================
# r720 Node
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: pve-r720
  namespace: traefik
spec:
  type: ExternalName
  externalName: 192.168.50.101
  ports:
    - name: https
      port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pve-r720
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`r720.pve.646499453.xyz`)
      services:
        - name: pve-r720
          port: 8006
  tls:
    passthrough: true

---
# ==========================================
# n100x8 Node
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: pve-n100x8
  namespace: traefik
spec:
  type: ExternalName
  externalName: 192.168.50.102
  ports:
    - name: https
      port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pve-n100x8
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`n100x8.pve.646499453.xyz`)
      services:
        - name: pve-n100x8
          port: 8006
  tls:
    passthrough: true

---
# ==========================================
# 3960x Node
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: pve-3960x
  namespace: traefik
spec:
  type: ExternalName
  externalName: 192.168.50.104
  ports:
    - name: https
      port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pve-3960x
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`3960x.pve.646499453.xyz`)
      services:
        - name: pve-3960x
          port: 8006
  tls:
    passthrough: true

---
# ==========================================
# 1920x Node
# ==========================================
apiVersion: v1
kind: Service
metadata:
  name: pve-1920x
  namespace: traefik
spec:
  type: ExternalName
  externalName: 192.168.50.105
  ports:
    - name: https
      port: 8006
      targetPort: 8006
      protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: pve-1920x
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: HostSNI(`1920x.pve.646499453.xyz`)
      services:
        - name: pve-1920x
          port: 8006
  tls:
    passthrough: true
