deployment:
  # -- Enable deployment
  enabled: true
  # -- Deployment or DaemonSet
  kind: DaemonSet


# @schema mergeProperties: true
ports:
  web:
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    port: 8443
    exposedPort: 8443
    http:
      tls:
        enabled: true

# 强制 Traefik 使用 MetalLB 池子里的第一个 IP，方便你在 Surge 里做 DNS 映射
service:
  type: LoadBalancer
  spec:
    loadBalancerIP: 192.168.50.230

providers:
  kubernetesCRD:
    enabled: true
    allowCrossNamespace: true
    allowExternalNameServices: true
  kubernetesIngress:
    enabled: true
    allowExternalNameServices: true