ingress:
  enabled: true
  ingressClassName: traefik
  hosts:
    - host: umami.646499453.xyz
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wildcards-646499453-xyz-tls
      hosts:
        - umami.646499453.xyz
  annotations:
    gethomepage.dev/enabled: '"true"'
    gethomepage.dev/name: '"Umami"'
    gethomepage.dev/description: '"Web Analytics"'
    gethomepage.dev/group: '"Services"'
    gethomepage.dev/icon: '"umami.png"'
    gethomepage.dev/href: '"https://umami.646499453.xyz"'

postgresql:
  enabled: false

umami:
  existingSecret: umami-secrets
  existingSecretKey: UMAMI_APP_SECRET
  extraEnv:
    - name: DATABASE_URL
      value: postgresql://$(UMAMI_DB_USER):$(UMAMI_DB_PASSWORD)@$(UMAMI_DB_HOST):5432/$(UMAMI_DB_NAME)
    - name: UMAMI_DB_USER
      valueFrom:
        secretKeyRef:
          name: umami-secrets
          key: UMAMI_DB_USER
    - name: UMAMI_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: umami-secrets
          key: UMAMI_DB_PASSWORD
    - name: UMAMI_DB_HOST
      valueFrom:
        secretKeyRef:
          name: umami-secrets
          key: UMAMI_DB_HOST
    - name: UMAMI_DB_NAME
      valueFrom:
        secretKeyRef:
          name: umami-secrets
          key: UMAMI_DB_NAME
database:
  url: ""
