---
- Repo:
    - TheWebsite:
        - icon: https://humblehouse.com.cn/favicon.ico
          href: https://github.com/HumbleHouse-com-cn/TheWebsite
    - Homelab-Infra Monolith Repo:
        - icon: sh-gitbundle-light.svg
          href: https://github.com/HumbleHouse-com-cn/IaC
    - Homelab-Talos-IaC Repo:
        - icon: sh-argo-cd.svg
          href: https://github.com/loushomelab/homelab-talos-iac
    - Homelab-PVE Repo:
        - icon: sh-hashicorp-terraform.svg
          href: https://github.com/loushomelab/homelab-pve
    - HASS-Langshi Repo:
        - icon: sh-home-assistant.svg
          href: https://github.com/loushomelab/hass-langshi-config
- Resources:
    - Doppler k8s Admin WebUI:
        - icon: sh-doppler.svg
          href: https://dashboard.doppler.com/workplace/006da931809ad4a28e6d/
    - HCP Terraform WebUI:
        - icon: sh-hashicorp-terraform.svg
          href: https://app.terraform.io/app/loushomelab/workspaces
    - Logo source for Homepage:
        - icon: sh-selfh-st.svg
          href: https://selfh.st/icons/
    - Renovate ArgoCD Repo:
        - icon: sh-renovate-bot.webp
          href: https://developer.mend.io/github/loushomelab/homelab-talos-iac
    - Cloudflare Admin WebUI (Login w/ Apple):
        - icon: sh-cloudflare.svg
          href: https://dash.cloudflare.com/
- My Websites:
    - HumbleHouse Official Website:
        - icon: https://humblehouse.com.cn/favicon.ico
          href: https://humblehouse.com.cn
    - Lou's Homelab Github Org Page:
        - icon: sh-github.svg
          href: https://github.com/loushomelab
    - HumbleHouse-com-cn Github Org Page:
        - icon: sh-github.svg
          href: https://github.com/HumbleHouse-com-cn