- Proxmox:
    - PVE-Cluster:
        - PVE-Homelab:
            href: https://r720.pve.646499453.xyz:8443
            widget:
                type: proxmox
                url: https://192.168.50.101:8006
                username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
                password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
        - Proxmox Backup Server:
            href: https://pbs.646499453.xyz:8443
            description: PBS installed with helper script as LXC
            showStats: true
            proxmoxNode: r720
            proxmoxVMID: 103
            proxmoxType: lxc
            widget:
                type: proxmoxbackupserver
                url: https://192.168.50.154:8007
                username: {{HOMEPAGE_VAR_PBS_USERNAME}}
                password: {{HOMEPAGE_VAR_PBS_PASSWORD}}
                datastore: pbstorage
    - PVE-Nodes:
        - 1920x:
            href: https://1920x.pve.646499453.xyz:8443
            showStats: true
            proxmoxNode: 1920x
            widget:
                type: proxmox
                url: https://192.168.50.105:8006
                username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
                password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
                node: 1920x
        - 3960x:
            href: https://3960x.pve.646499453.xyz:8443
            showStats: true
            proxmoxNode: 3960x
            widget:
                type: proxmox
                url: https://192.168.50.104:8006
                username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
                password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
                node: 3960x
        - n100x8:
            href: https://n100x8.pve.646499453.xyz:8443
            showStats: true
            proxmoxNode: n100x8
            widget:
                type: proxmox
                url: https://192.168.50.102:8006
                username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
                password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
                node: n100x8
        - r720:
            href: https://r720.pve.646499453.xyz:8443
            showStats: true
            proxmoxNode: r720
            widget:
                type: proxmox
                url: https://192.168.50.101:8006
                username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
                password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
                node: r720

- NAS:
    - Synology:
        description: Synology DSM
        href: https://ds920.646499453.xyz:8443
        icon: synology
        widget:
            type: diskstation
            url: http://192.168.50.77:5000
            username: {{HOMEPAGE_VAR_SYNOLOGY_USERNAME}}
            password: {{HOMEPAGE_VAR_SYNOLOGY_PASSWORD}}
    - TrueNAS:
        description: NAS Storage
        href: https://truenas.646499453.xyz:8443
        showStats: true
        proxmoxNode: n100x8
        proxmoxVMID: 1300
        proxmoxType: qemu
        widget:
            type: truenas
            url: https://192.168.50.76
            key: {{HOMEPAGE_VAR_TRUENAS_API_KEY}}
            version: 2

- Network:
    - Unifi:
    description: Network Controller
    href: https://unifi.646499453.xyz:8443
    widget:
        type: unifi
        url: https://192.168.50.1
        site: 朗诗[Cloud Gateway Max]
        key: {{HOMEPAGE_VAR_UNIFI_API_KEY}}

- IOT:
    - Langshi:
        description: Home Assistant
        href: https://langshi.hass.646499453.xyz:8443
        widget:
            type: homeassistant
            url: http://192.168.50.120:8123
            key: {{HOMEPAGE_VAR_HASS_LANGSHI_TOKEN}}

- Database:
    - TrueNAS MinIO:
        description: S3 Object Storage on TrueNAS
        href: https://minio.truenas.646499453.xyz:8443
