- Procmox:
    - PVE-Cluster:
        - PVE-Homelab:
            icon: sh-proxmox.svg
            pod-selector: ""
            widget:
                href: https://r720.pve.646499453.xyz:8443
                type: proxmox
                url: https://192.168.50.101:8006
                username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
                password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}