- Hosts:
    - PVE-Cluster:
        - PVE-Homelab:
            icon: sh-proxmox.svg
            description: Cluster Overall Status
            href: https://r720.pve.646499453.xyz:8443
            widget:
                type: proxmox
                url: https://192.168.50.101:8006
                username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
                password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
        - Proxmox Backup Server:
            icon: sh-linux-containers-lxc.svg
            siteMonitor: https://192.168.50.154:8007
            href: https://pbs.646499453.xyz:8443
            description: PBS installed with helper script as LXC
            showStats: true
            proxmoxNode: 3960x
            proxmoxVMID: 103
            proxmoxType: lxc
            widget:
                type: proxmoxbackupserver
                url: https://192.168.50.154:8007
                username: {{HOMEPAGE_VAR_PBS_USERNAME}}
                password: {{HOMEPAGE_VAR_PBS_PASSWORD}}
                datastore: pbstorage
    - NAS:
        - Synology:
            description: Synology DSM
            href: https://ds920.646499453.xyz:8443
            siteMonitor: https://192.168.50.77:5001
            icon: sh-synology.svg
            widget:
                type: diskstation
                url: http://192.168.50.77:5000
                username: {{HOMEPAGE_VAR_SYNOLOGY_USERNAME}}
                password: {{HOMEPAGE_VAR_SYNOLOGY_PASSWORD}}
        - TrueNAS:
            description: NAS Storage
            href: https://truenas.646499453.xyz:8443
            siteMonitor: https://192.168.50.76
            showStats: true
            icon: sh-truenas-scale.svg
            proxmoxNode: n100x8
            proxmoxVMID: 1300
            proxmoxType: qemu
            widget:
                type: truenas
                url: https://192.168.50.76
                key: {{HOMEPAGE_VAR_TRUENAS_API_KEY}}
                version: 2
- PVE-Nodes:
    - 1920x:
        icon: sh-proxmox.svg
        href: https://1920x.pve.646499453.xyz:8443
        siteMonitor: https://192.168.50.105:8006
        showStats: true
        proxmoxNode: 1920x
        widget:
            type: proxmox
            url: https://192.168.50.105:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: 1920x
    - 3960x:
        icon: sh-proxmox.svg
        href: https://3960x.pve.646499453.xyz:8443
        siteMonitor: https://192.168.50.104:8006
        showStats: true
        proxmoxNode: 3960x
        widget:
            type: proxmox
            url: https://192.168.50.104:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: 3960x
    - n100x8:
        icon: sh-proxmox.svg
        href: https://n100x8.pve.646499453.xyz:8443
        siteMonitor: https://192.168.50.102:8006
        showStats: true
        proxmoxNode: n100x8
        widget:
            type: proxmox
            url: https://192.168.50.102:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: n100x8
    - r720:
        icon: sh-proxmox.svg
        href: https://r720.pve.646499453.xyz:8443
        siteMonitor: https://192.168.50.101:8006
        showStats: true
        proxmoxNode: r720
        widget:
            type: proxmox
            url: https://192.168.50.101:8006
            username: {{HOMEPAGE_VAR_PROXMOX_USERNAME}}
            password: {{HOMEPAGE_VAR_PROXMOX_PASSWORD}}
            node: r720

- CI/CD:
    - Terraform Agent:
        description: LXC in PVE Cluster
        href: https://app.terraform.io/app/loushomelab/workspaces/homelab-pve/runs/
        icon: sh-hashicorp-terraform.svg
        ping: 192.168.50.200
        showStats: true
        proxmoxNode: 3960x
        proxmoxVMID: 200
        proxmoxType: lxc
        widget:
- Network:
    - Unifi:
        description: Network Controller
        href: https://unifi.ui.com
        icon: sh-ubiquiti-unifi.svg
        siteMonitor: https://192.168.50.1
        widget:
            type: unifi
            url: https://192.168.50.1
            key: {{HOMEPAGE_VAR_UNIFI_API_KEY}}

- IOT:
    - Langshi:
        description: Home Assistant
        href: https://hass.646499453.xyz:8443
        icon: sh-home-assistant.svg
        siteMonitor: http://192.168.50.120
        showStats: true
        proxmoxNode: 3960x
        proxmoxVMID: 104
        proxmoxType: qemu
        widget:
            type: homeassistant
            url: http://192.168.50.120
            key: {{HOMEPAGE_VAR_HASS_LANGSHI_TOKEN}}

- Database:
    - PostgreSQL Authentik:
        description: LXC database dedicated to Authentik
        icon: sh-postgresql.svg
        ping: 192.168.50.151
        showStats: true
        proxmoxNode: 3960x
        proxmoxVMID: 101
        proxmoxType: lxc
    - Redis Authentik:
        description: LXC database dedicated to Authentik
        icon: sh-redis.svg
        ping: 192.168.50.152
        showStats: true
        proxmoxNode: 3960x
        proxmoxVMID: 102
        proxmoxType: lxc
    - PostgreSQL Observibility:
        description: LXC for Monitoring Applications
        icon: sh-postgresql.svg
        ping: 192.168.50.153
        showStats: true
        proxmoxNode: 3960x
        proxmoxVMID: 103
        proxmoxType: lxc
    - TrueNAS MinIO:
        description: S3 Object Storage on TrueNAS
        icon: sh-minio.svg
        href: https://minio.truenas.646499453.xyz:8443
        siteMonitor: https://192.168.50.76:443
