title: Lous Homelab Dashboard
background:
  image: https://images.unsplash.com/photo-1780467763551-f182a0d55c9f?q=80&w=2940&auto=format&fit=crop
  blur: sm
  saturate: '50'
  brightness: '50'
  opacity: '75'
favicon: https://humblehouse.com.cn/favicon.ico
headerStyle: boxedWidgets
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
  provider: google
layout:
  Hosts:
    style: row
    columns: 2
    PVE-Cluster:
    NAS:
    Network:
    IOT:
  PVE-Nodes:
    style: row
    columns: 4
  Kubernetes:
    style: row
    columns: 2
    Identity:
    CI/CD:
    Dashboards:
    Monitoring:
  Database:
    style: row
    columns: 4