title: "Lous Homelab Dashboard"
background:
  image: https://images.unsplash.com/photo-1780467763551-f182a0d55c9f?q=80&w=2940&auto=format&fit=crop
  blur: "sm"
  saturate: "50"
  brightness: "50"
  opacity: "50"
favicon: https://humblehouse.com.cn/favicon.ico
headerStyle: boxedWidgets
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
  provider: google # google, duckduckgo, bing, baidu, brave or custom
layout:
  Storage:
    style: row
    columns: 3
  Database:
    style: row
    columns: 3
  Monitoring:
    style: row
    columns: 3
  Self-Host Services:
    style: row
    columns: 3
    Identity:
      style: row
      columns: 1
    CI/CD:
      style: row
      columns: 1
    Networking:
      style: row
      columns: 1
    Dashboards:
      style: row
      columns: 1
  PVE:
    style: row
    columns: 3
  Identity Homelab:
    style: row
    columns: 1
  IOT:
    style: row
    columns: 3