- kubernetes:
    cluster:
      show: true
      cpu: true
      memory: true
      showLabel: true
      label: "Talos-Homelab"
    nodes:
      show: true
      cpu: true
      memory: true
      showLabel: true
- datetime:
    text_size: xl
    locale: ch
    format:
      weekday: short
      month: short
      day: numeric
      hour: 2-digit
      minute: 2-digit
      hour12: false
- unifi_console:
    url: https://192.168.50.1
    site: 朗诗[Cloud Gateway Max]
    key: {{HOMEPAGE_VAR_UNIFI_API_KEY}}
- search:
    provider: [google, duckduckgo, bing, baidu, brave]
    focus: true # Optional, will set focus to the search bar on page load
    showSearchSuggestions: true # Optional, will show search suggestions. Defaults to false
    target: _blank # One of _self, _blank, _parent or _top