apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: 'https://github.com/loushomelab/homelab-talos-iac.git'
    path: argocd/configs/security/external-secrets
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
