apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: ghcr.io/grafana/helm-charts
    chart: grafana-operator
    targetRevision: 5.25.0
    helm:
      valuesObject:
        namespaceScope: false
        watchNamespaces: monitoring
        rbac:
          create: true
          useClusterRole: true
        crds:
          immutable: false
  destination:
    server: https://kubernetes.default.svc
    namespace: grafana-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
