apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
spec:
  project: infra
  source:
    repoURL: 'ghcr.io/emberstack/helm-charts'
    targetRevision: 10.0.65
    chart: reflector
    helm:
      valuesObject:
        extraEnv:
          - name: TZ
            value: Asia/Shanghai
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
