apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: '5'
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: authentik
  namespace: argocd
spec:
  destination:
    namespace: authentik
    server: https://kubernetes.default.svc
  project: apps
  source:
    chart: authentik
    helm:
      values: "authentik:\n  envFrom:\n  - secretRef:\n      name: authentik-db-credentials\n\
        \  - secretRef:\n      name: authentik-secret-key\n  - secretRef:\n      name:\
        \ authentik-oidc-credentials\n  - secretRef:\n      name: authentik-blueprint-secrets\n\
        postgresql:\n  enabled: false\nredis:\n  enabled: false\nserver:\n  metrics:\n\
        \    enabled: true\n    serviceMonitor:\n      enabled: true\n      labels:\n\
        \        release: kube-prometheus-stack\n  envFrom:\n  - secretRef:\n    \
        \  name: authentik-db-credentials\n  - secretRef:\n      name: authentik-secret-key\n\
        \  - secretRef:\n      name: authentik-oidc-credentials\n  - secretRef:\n\
        \      name: authentik-blueprint-secrets\n  volumes:\n  - name: sso-authentik-blueprints\n\
        \    configMap:\n      name: sso-authentik-blueprints\n  volumeMounts:\n \
        \ - name: sso-authentik-blueprints\n    mountPath: /blueprints/mounted/cm-sso-authentik-blueprints\n\
        \    readOnly: true\n  ingress:\n    ingressClassName: ''\n    annotations:\n\
        \      traefik.ingress.kubernetes.io/router.tls: 'true'\n      gethomepage.dev/enabled:\
        \ 'true'\n      gethomepage.dev/name: Authentik\n      gethomepage.dev/description:\
        \ SSO & Identity Provider\n      gethomepage.dev/group: Identity\n      gethomepage.dev/icon:\
        \ authentik.png\n      gethomepage.dev/app: authentik\n      gethomepage.dev/widget.type:\
        \ authentik\n      gethomepage.dev/widget.version: '2'\n      gethomepage.dev/widget.url:\
        \ https://authentik.646499453.xyz:8443\n      gethomepage.dev/widget.key:\
        \ '{{HOMEPAGE_VAR_AUTHENTIK_API_KEY}}'\n    enabled: true\n    hosts:\n  \
        \  - authentik.646499453.xyz\n    tls:\n\
        \    - hosts:\n      - authentik.646499453.xyz\n      secretName: wildcard-646499453-crt\n\
        worker:\n  metrics:\n    enabled: true\n    serviceMonitor:\n      enabled:\
        \ true\n      labels:\n        release: kube-prometheus-stack\n  envFrom:\n\
        \  - secretRef:\n      name: authentik-db-credentials\n  - secretRef:\n  \
        \    name: authentik-secret-key\n  - secretRef:\n      name: authentik-oidc-credentials\n\
        \  - secretRef:\n      name: authentik-blueprint-secrets\nblueprints:\n  configMaps:\n\
        \  - sso-authentik-blueprints\n"
    repoURL: https://charts.goauthentik.io
    targetRevision: 2026.5.3
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
