apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  tokenSecret:
    name: doppler-token-shared
  managedSecret:
    name: homepage-secrets
    namespace: homepage
  project: k8s
  config: prd
  processors:
    HOMEPAGE_VAR_PROXMOX_USERNAME:
      type: plain
    HOMEPAGE_VAR_PROXMOX_PASSWORD:
      type: plain
