apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-configs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "15" # After doppler operator but before workloads
spec:
  project: infra
  source:
    repoURL: 'https://github.com/loushomelab/homelab-talos-iac.git'
    targetRevision: HEAD
    path: argocd/configs/infrastructure/argocd/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
