apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-configs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: 'https://github.com/loushomelab/homelab-talos-iac.git'
    targetRevision: HEAD
    path: argocd/configs/infrastructure/cert-manager/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
