apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    link.argocd.argoproj.io/external-link: https://longhorn.646499453.xyz:8443
spec:
  project: infra
  sources:
    - repoURL: 'https://charts.longhorn.io'
      chart: longhorn
      targetRevision: 1.12.1
      helm:
        valuesObject:
          preUpgradeChecker:
            jobEnabled: false
          defaultSettings:
            defaultDataPath: /var/lib/longhorn
            replicaSoftAntiAffinity: true
            defaultReplicaCount: 3
          persistence:
            defaultClass: true
            defaultClassReplicaCount: 3
            reclaimPolicy: Delete
          ingress:
            enabled: true
            ingressClassName: traefik
            host: longhorn.646499453.xyz
            tls: true
            tlsSecret: wildcards-646499453-xyz-tls
            annotations:
              traefik.ingress.kubernetes.io/router.middlewares: traefik-authentik-forwardauth@kubernetescrd
              gethomepage.dev/enabled: "true"
              gethomepage.dev/name: "Longhorn"
              gethomepage.dev/description: "Distributed Block Storage"
              gethomepage.dev/group: "Storage"
              gethomepage.dev/icon: "sh-longhorn.svg"
              gethomepage.dev/href: "https://longhorn.646499453.xyz:8443"
              gethomepage.dev/pod-selector: "app=longhorn-ui"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
