apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: umami-secrets
  namespace: umami
spec:
  tokenSecret:
    name: doppler-token-shared
  managedSecret:
    name: umami-secrets
    namespace: umami
  project: k8s
  config: prd
  processors:
    DB_OBS_POSTGRESQL__HOST:
      asName: UMAMI_DB_HOST
      type: plain
    UMAMI_POSTGRESQL__NAME:
      asName: UMAMI_DB_NAME
      type: plain
    UMAMI_POSTGRESQL__USER:
      asName: UMAMI_DB_USER
      type: plain
    UMAMI_POSTGRESQL__PASSWORD:
      asName: UMAMI_DB_PASSWORD
      type: plain
    UMAMI_APP_SECRET:
      asName: UMAMI_APP_SECRET
      type: plain
