apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  url: https://argocd.646499453.xyz:8443
  dex.config: |
    connectors:
    - config:
        issuer: https://authentik.646499453.xyz:8443/application/o/argocd/
        clientID: argocd
        clientSecret: $argocd-oidc-secret:oidc.authentik.clientSecret
        insecureEnableGroups: true
        scopes:
          - openid
          - profile
          - email
          - groups
      name: authentik
      type: oidc
      id: authentik
