apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: argocd-secrets
  namespace: argocd
spec:
  tokenSecret:
    name: doppler-token-shared
  managedSecret:
    name: argocd-secret
    namespace: argocd
  project: k8s
  config: prd
  processors:
    AUTHENTIK_OIDC_ARGOCD_SECRET:
      asName: oidc.authentik.clientSecret
      type: plain
