apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-server
    app.kubernetes.io/part-of: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`argocd.646499453.xyz`)
      kind: Rule
      services:
        - name: argocd-server
          port: 80
  tls:
    secretName: wildcards-646499453-xyz-tls
